# Generated by Django 3.0.5 on 2020-05-08 11:18

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0005_auto_20200508_0237'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='data_meta',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='repository',
            name='data_source',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
